
services:
  - type: web
    name: tradingview-binance-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: BINANCE_API_KEY
        value: your_binance_api_key
      - key: BINANCE_API_SECRET
        value: your_binance_api_secret
      - key: WEBHOOK_SECRET
        value: your_webhook_secret
